### ISSUE TITLE
hyper-parameter searching

### ISSUE THREAD

**Issue by Lincoln93** [dreamquark-ai/tabnet#146]
Is it possible to do hyper-parameter searching like `GridSearchCV` or `RandomSearchCV` for tabnet classifer or regressor?

**Comment by Optimox** [comment]
sure, but you'll need to make a small wrapper so that it would work.

Please have a look a this issue : https://github.com/dreamquark-ai/tabnet/issues/80

The last answer from @Hartorn gives a nice notebook to show how to do it.
I guarantee that it's safe to download.

But the main idea is that `GridSearchCV` or `RandomSearchCV` would not have any specific fit params so you need to do something like

```
class TabNetTuner(TabNetClassifier):
    def fit(self, X, y, *args, **kwargs):
        # Dirty trick => would be better to add n_d in grid, or fix it in __init__ of tuner
        self.n_d = self.n_a
        X_train, X_valid, y_train, y_valid = train_test_split(
            X, y, test_size=0.2, random_state=0, shuffle=True, stratify=y
        )
        return super().fit(
            X_train,
            y_train,
            patience=20,
            X_valid=X_valid,
            y_valid=y_valid,
            num_workers=num_workers,
            max_epochs=1000,
            batch_size=1024,
            virtual_batch_size=128,
        )
```
Before using the grid.

**Comment by balazsgonczy** [comment]
It is possible to do with Optuna library. If I have finished my project then I'll share it on my github account check it out then!
