### ISSUE TITLE
Final explain_matrix doesn't seems right.

### ISSUE THREAD

**Issue by carter840826** [dreamquark-ai/tabnet#180]
From the example notebook, I tried plot final explain_matrix.
And here is my question.

![image](https://user-images.githubusercontent.com/57344651/92456945-27311b80-f1f6-11ea-9007-a3eed90ee79a.png)
As fig showing above, the sum of mask value form single prediction isn't 1.
Just like:
![image](https://user-images.githubusercontent.com/57344651/92457166-7a0ad300-f1f6-11ea-9505-f8c21ace4e81.png)
,while some didn't have this problem:
![image](https://user-images.githubusercontent.com/57344651/92457288-9eff4600-f1f6-11ea-9532-85fd88538a6e.png)

Thanks for helping!

**Comment by Optimox** [comment]
Hi @carter840826,

Thanks for reporting this.

Is there a way to reproduce this in order to investigate more?

Could you share a minimal reproducible code showing this? Or at least give more information on your experiment?

Thanks!

**Comment by carter840826** [comment]
Hi,

What I did just was the example you provided.
https://github.com/dreamquark-ai/tabnet/blob/develop/regression_example.ipynb

![image](https://user-images.githubusercontent.com/57344651/92458698-55aff600-f1f8-11ea-8d9c-e6e7fec30601.png)
As you can see, the sum of mask value from single prediction isn't 1.
Instead of what paper shows:
![image](https://user-images.githubusercontent.com/57344651/92458930-9f98dc00-f1f8-11ea-8d05-0cbd203b8792.png)

Thanks for replying!

**Comment by Optimox** [comment]
Yes you are right the implementation differs from the original paper, we are not performing the normalization. As you can see from your examples the rows are not summing to 1 (even the 'working' one)

As a quick work around you can do it very easily by dividing by the sum of each row and you'll get the same results as in the paper.

Why don't we do it? I think it's because I don't fully agree with the original paper on this.

Let me explain:
- I see a flaw in the definition of the explanation matrix. The fact of multiplying the mask with eta the sum of the n_d relu before final mapping in order to give feature importance can create a very weird behavior : if all the ReLUs are saturated and equal to 0 you're model will output 0. It's ok to output 0 right (as long as you expect 0 as your output)? but then your explanation matrix will give 0 importance to all features, disregarding the masks that were used in order to saturate the ReLus. I agree it's a degenerated case but sometimes you'll get all feature importances equal to 0 (and then you'll get a ZeroDivisionError). This is the reason why the explain method outputs also the masks, so that people that want to take a closer look can do it easily.
- With that said, we are performing the normalization for feature importance, so the error would pop out anyway in the current implementation, so it would make sense to normalize things as in the paper.
- According to the paper, we don't propagate the importance through the final mapping, so the given importance is not really a sensitivity importance. It's really hard to define what an explanation is, but I would also trust the normalized sum of the masks without multiplying with the sum of ReLUs.

Short answer:
- you are right, we are missing the normalization (and should probably add it)
- if you simply normalize your output row by row you'll get the paper's results
- there's still open debate on research on what would be the best explanation of the model's output

**Comment by carter840826** [comment]
I see.
Thanks a lot for explanation!!
