### ISSUE TITLE
ValueError in loss_fn .

### ISSUE THREAD

**Issue by Rajsuryan-Singh** [dreamquark-ai/tabnet#239]
The following error shows up when I try training the model on the lish_moa dataset. 
ValueError: y_true contains only one label (0). Please provide the true labels explicitly through the labels argument. 

I made some changes to the example notebook and I'm attaching the modified notebook for reference. 

**What is the current behavior?**
The aforementioned error shows up when I try to train the model with validation, it works normally if I don't use validation. 
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Download the following notebook - https://github.com/Rajsuryan-Singh/Mechanism-of-Action-Prediction/blob/master/tabnetmultitaskclassifier.ipynb)
2. Run all the cells until the training step
3. The error can be observed
**Expected behavior**

It is expected to train the model, as it does in the multilabel example in this repository. 
**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

**Comment by Optimox** [comment]
Well I made several public notebooks showing how to make it work with MOA dataset.

The error seems clear to me, since you only have one value in a target, you can’t compute the log loss. You should use a custom log loss that accepts only one label. The error comes from the sklearn log_loss function.

Please refer to the public notebooks share on the challenge.

**Comment by Optimox** [comment]
I'm closing this, feel free to reopen if needed.
