### ISSUE TITLE
tabnet classifier (google colab)

### ISSUE THREAD

**Issue by pianonyy** [dreamquark-ai/tabnet#274]
**Describe the bug**
Facing troubles with cuda, when I'm trying to use google colab

**What is the current behavior?**

Gpu enviroment, tabnetclassiffier doesn't work 

**Screenshots**

![image](https://user-images.githubusercontent.com/48867176/111288424-38e7f580-8655-11eb-85b8-0c45f1fb2ac9.png)

**Comment by Optimox** [comment]
I think we are missing some information in order to help you.

The line `transf.fit(...)` seems a bit weird, could you share your code without sharing a screen shot of it, but actually copy pasting in?

Did you check for Nan values in your train and validation set? This error often comes with missing values. Also if you switch your model to `cpu` you'll get a clearer error.

**Comment by pianonyy** [comment]
Sure, thanks a lot!

**Comment by Optimox** [comment]
@pianonyy did you solve your problem? What was it?
