### ISSUE TITLE
What is the intention of this part in TabNetDecoder?

### ISSUE THREAD

**Issue by yoshihisa-furusawa** [dreamquark-ai/tabnet#291]
Your code is neatly organized, easy to read, and very useful in helping me understand the paper.
But I am not sure this point.
Why do you ignore outputs from feat_transformers method?

https://github.com/dreamquark-ai/tabnet/blob/8c3b7951642f62e7449bb95875b5265d4b89148e/pytorch_tabnet/tab_network.py#L278

I Intuitively think that this part should be  bellow.

```python
x = self.feat_transformers[step_nb](step_output) 
x = self.reconstruction_layers[step_nb](x)
```

**Comment by Optimox** [comment]
Hello @yoshihisa-furusawa,

Indeed there is a problem with that line, thanks for pointing it.

I think this line `x = self.feat_transformers[step_nb](step_output)` should have been commented (and we should not define feat transformers modules for decoder). I think I tried two versions and forgot to clean the code in the end.

What happens here is that you can give more power to the decoder to do its job by adding a few extra feat transformer layers, however those layers won't be of any use when training the final tabnet model because those layers only belong to the pretrainer, so in the end I decided not to use them.

So in the end, I think there is a problem because we are defining layers that we never use, which is bad. However I think those layers should not exist and we should not use them. I'll make the changes soon.

**Comment by Optimox** [comment]
I think you are right, I've probably taken too much freedom in the current implementation and what's currently available differs a lot with the original paper. 

I'll create a PR soon and ping you when it's done (should be fairly quick to add one feat transformer layer and a final layer).

Thanks for your useful feedback!

**Comment by Optimox** [comment]
Hello @yoshihisa-furusawa I created a PR #302, if you want to have a look and let me know if it feels closer to what the paper presents I'll be happy to hear from you. Thanks!
