### ISSUE TITLE
feature_importances_ not preserved after reloading the model

### ISSUE THREAD

**Issue by albert-ying** [dreamquark-ai/tabnet#298]
Hi, I saved and reload the model I trained as following

```
# save tabnet model
saving_path_name = "./result/12_tabnet_model_tms_80%_model"
saved_filepath = clf.save_model(saving_path_name)

# define new model with basic parameters and load state dict weights
saved_filepath = "./result/12_tabnet_model_tms_80%_model.zip"
clf = TabNetRegressor()
clf.load_model(saved_filepath)
```
But when I try to call the feature importance of the model it gives me the error
```
## feature importance
vips = clf.feature_importances_
```
```
AttributeError: 'TabNetRegressor' object has no attribute 'feature_importances_'
```
The error preserved even after I run `clf.predict` on the test data set.

I'm wondering if there is easy way to restore the `feature_importances_`? Do I have to run `clf.fit` on training dataset again?

**Comment by xichens** [comment]
So the `feature_importances_` is created at the end of `fit` as can be seen [here](https://github.com/dreamquark-ai/tabnet/blob/5e4e8099335ebddd6b297b16aa40cf0bad145b4a/pytorch_tabnet/abstract_model.py#L242)
```
self._compute_feature_importances(train_dataloader)
```
where `train_dataloader` is created [here](https://github.com/dreamquark-ai/tabnet/blob/5e4e8099335ebddd6b297b16aa40cf0bad145b4a/pytorch_tabnet/abstract_model.py#L195) by
```
 train_dataloader, valid_dataloaders = self._construct_loaders(X_train, y_train, eval_set)
```

So if you load your `X_train, y_train` and `eval_set` (optional), you can recalculate the importance scores by
```
train_dataloader, valid_dataloaders = clf._construct_loaders(X_train, y_train, eval_set)
clf._compute_feature_importances(train_dataloader)
```

*(Haven't tested myself since I'm away from my working machine)*

**Comment by albert-ying** [comment]
Thank you! @xichens
