### ISSUE TITLE
Extend Tabnet to Capture Temporal Dependency

### ISSUE THREAD

**Issue by tim5go** [dreamquark-ai/tabnet#304]
## Feature request

**What is the expected behavior?**
To capture temporal dependency between tabular records.

**What is motivation or use case for adding/changing the behavior?**
Tabular data, such as customers' transactional records, exhibit temporal dependency.
To capture it, one could design lagged features / time-aggregated features.
However, it is not ideal as it involves manual feature engineering.

**How should this be implemented in your opinion?**
Inspired by TabFormer (https://arxiv.org/abs/2011.01843), it may be possible to implement an extra sequential module to handle it.

**Are you willing to work on this yourself?**
yes (but need help)

**Comment by eduardocarvp** [comment]
Hello @tim5go ,

I had a very quick look at the paper, but I'm not sure how related this is to TabNet. At first sight, it looks like a different algorithm altogether and, more generally, I'm not sure handling temporal data remains in the scope of TabNet. But maybe I just didn't get the idea, I will read in detail as soon as I have the time!

**Comment by Optimox** [comment]
Hello @tim5go,

I agree with @eduardocarvp, this is really out of scope for the tabnet repo.

It would require a lot of new formalism to specifiy that we are in a time serie setting, and I don't see how it would relate to the orginal TabNet.

Feel free to open a PR with preliminary work so that we can discuss concretely based on the code.
