### ISSUE TITLE
Session based embeddings

### ISSUE THREAD

**Issue by sevstafiev** [dreamquark-ai/tabnet#309]
Hi! I have a table with user sessions for classification task. Tabnet seems to be perfect for this. However, I am working with user sessions and would like to inline averaging row embeddings over the session_id value. How can I do that?

<html>
<body>

user_crm_id | session_id | session_client_id | session_interaction_action | session_interaction_time | session_interaction_context_screen_type | hit_id | session_interaction_hit_number | session_id_tech | session_device_category | session_device_os | session_device_browser | target
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
None | 1045733319.1622542421_1622543204882 | 1045733319.1622542421 | add | 2021-06-01 10:10:10 | ProductPage | 4491390407065077845_1_10 | 10 | 4491390407065077845_1 | mobile | Android | Chrome | 1
None | 1045733319.1622542421_1622543204882 | 1045733319.1622542421 | view | 2021-06-01 10:25:56 | InfoPage | 4491390407065077845_1_36 | 36 | 4491390407065077845_1 | mobile | Android | Chrome | 1
55073669 | 1036442672.1617017987_1622554608094 | 1036442672.1617017987 | view | 2021-06-01 13:32:44 | Main | 4451487382035872899_17_1 | 1 | 4451487382035872899_17 | mobile | Android | Chrome | 0
55073669 | 1036442672.1617017987_1622554608094 | 1036442672.1617017987 | view | 2021-06-01 13:35:21 | InfoPage | 4451487382035872899_17_27 | 27 | 4451487382035872899_17 | mobile | Android | Chrome | 0

</body>
</html>

**Comment by eduardocarvp** [comment]
Hello @sevstafiev ,

I'm not sure I understand, you'd like to average the outputs of the embedding layer for a same session_id during training?
Are the targets always the same in this case?

**Comment by sevstafiev** [comment]
Yep
Yes, targets always the same for each session_id

**Comment by sevstafiev** [comment]
So, my goal is to tell, based on the session, whether the user will return after it or not.

**Comment by Optimox** [comment]
Hello @sevstafiev,

Your problem seems to be a pre-processing issue, not something related to TabNet or embeddings.

What you need to do is to find a way of writting all the information for a session into one line. It's mostly feature engineering, you could try things like:
- number of actions
- time between first and last action
- depth of search inside your website
- count of actions for each categories
- many more things...

Once you've found a way to aggregate the information into one line for each session_id you won't even use this ID to train the model, no embeddings are needed for the session_id.

Feel free to share more information if I missed something specific to TabNet. I'll leave this open for sometime and close it later.

**Comment by sevstafiev** [comment]
Thanks!
I thought average embeddings would be a cool aggregation for sessions which will allow not to lose information unlike feature engineering. It seems that this cannot be built into the model in any way?

**Comment by Optimox** [comment]
I think you probably lack information at the action level in order to predict if someone is going to come back or not. So averaging on session_id does not sound like a good idea to me (I don't know anything about the data so I might be wrong).

For sure averaging embeddings is not feasible with TabNet. I'm closing this, good luck with your dataset!

**Comment by eduardocarvp** [comment]
I agree that this is mostly a transformation/feature engineering problem.
But I don't think we can do anything at the level of TabNet implementation and we'd probably steer too far from the original implementation.
Good luck on your project!

**Comment by sevstafiev** [comment]
Thanks!

**Comment by zippeurfou** [comment]
@Optimox We could imagine having something like an [embedding bag](https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html) for this cases. This might not be optimal but can potentially help for cases where you have inputs of variable sizes.

**Comment by Optimox** [comment]
I did not know about embedding bags, in what context is it used?

Sure dealing with inputs that vary in size looks great but at least for classical tabular approaches I don't see how it would work. If you end up with varying sizes for your inputs you should probably look into Graph Neural Networks which seem flexible enough to work in this setting.
