### ISSUE TITLE
How does the fc shared?

### ISSUE THREAD

**Issue by XimGao** [dreamquark-ai/tabnet#351]
From the previous questions, I know that only fc is shared in the feature transformer.
But I have a question about it, that is, how does the FC realize the parameter sharing?

By torch.nn.ModuleList() ?

In the define of self.fc, they are exactly same.

**Comment by Optimox** [comment]
Hello @XimGao,

Everything depends on the network architecture, when we are talking about a "shared layer" it means that there is one layer involved at different steps in the forward pass. The feature transformers are different at every step, but actually they share some layers and the model uses the same layers at each step. When performing the backward pass and the optimization step this means that the changes at step 1 will also change steps 2, 3, 4 etc... because they share the same layers.

In practice inside the code everything happens inside the ` forward` (just pseudo code): 
```
def forward(self, x):
    # first step
    x = self.shared_layer(x)
    x = self.step_one_layer(x)
    # second step
    x = self.shared_layer(x)
    x = self.step_two_layer(x)
```
In the above example, you can say that you have two similar steps with a shared layer or shared weights (the weights of the `shared_layer` which could be anything : convolution, linear or any transformation)

Let me know if this makes it clearer or not.

**Comment by XimGao** [comment]
Thanks for your reply so quickly, your explain is so clear that the question  becomes easier，and now I understand about that the shared layers how does realized.
