### ISSUE TITLE
What exactly local importance features value represents?

### ISSUE THREAD

**Issue by Abhinav43** [dreamquark-ai/tabnet#353]
Hello TABnet developers: I have two questions regarding the model training & interpretability part

1. How do you handle a dataset which contains both the continuous and categorical variables at the same time?

2. if I have two columns as x1, x2 then I am looking for a way that gives me an interpretability score for each column of each row, for example :

if my data looks like this

![Screenshot 2022-01-13 at 11 00 20 PM](https://user-images.githubusercontent.com/49252667/149630104-731c5e54-c551-4e44-ba09-1f5d142a7630.png)

now I train the model and get the global importance features such as :
```
clf.feature_importances_
array([0.22520029, 0.77479971])
```
But I want the feature importance for each row, so I tried the local importance function:

`explain_matrix, masks = clf.explain(X_test)`

Which gives me values like this:

```
array([[ 64.57525635,  52.24457932],
       [ 23.78452682, 258.87109375],
       [108.12106323,  19.93586349],
       ...,
       [109.72072601,  17.49860764],
       [ 58.51595688,  15.00261879],
       [ 35.38527298,  24.35892487]])
```

I am not able to understand the values, I wanted the sum of feature importance of each row to be 1 same as global feature importance ( 0.22520029 + 0.77479971 = 1.0 ) but these values are not summing up to 1  (   64.57525635 + 52.24457932 ! = 1.0 ) Could anyone explain this and also how I can get feature importance per row which sums up 1?

**Comment by Optimox** [comment]
Hello,

For the first question:
If you have numerical and categorical variable you’ll need to specify which columns are categorical (cat_idx), the number of categories (cat_dim) and the dimension of the embedding you want to use (emb_dim).
Then the model will train with both categorical and numerical variable, only embedding the categorical one. When you get the importance for a categorical variable, it’s actually the summed importance of the corresponding embedding.

About the second question:
You are doing the correct thing, just divide by the sum of each row to get a relative importance that sums to 1.
We did not perform this stage automatically so that if one wants to compare importance across rows it’s still possible. But the original paper simply divided by the sum which is very easy to do.

Hope this helps.

Best

**Comment by eduardocarvp** [comment]
Just to complement @Optimox's answer:

You can see an example here https://github.com/dreamquark-ai/tabnet/blob/develop/census_example.ipynb where we have an example with categorical features. Note that in this case, if the embedding dimension is larger than one we will sum all the embedding values to reduce back the importance to one single value.
