### ISSUE TITLE
Super slow training on GPU

### ISSUE THREAD

**Issue by jpgard** [dreamquark-ai/tabnet#391]
Thanks for the amazing tool! I am looking for help debugging poor performance on GPU. I am not sure whether this is due to a poor choice of hyperparameters, or the library itself. Any suggestions/workarounds would be appreciated.

**Describe the bug**
I am training a tabnet on a dataset of around 1.5M examples and 30 features, on a single NVIDIA RTX 2080 Ti GPU with 11GB of RAM. The training is *extremely* slow,  around 15-20min per epoch. For reference, a single epoch of a 9-layer MLP with 512 nodes per unit takes mere seconds with the same dataset and code.

**What is the current behavior?**

See above. Training is far slower than expected. A single training epoch takes around 15-20 minutes, with the hyperparameters listed below.

When training starts, I can see `Device used : cuda` in the console, and can see that the model is indeed on GPU from the output of `nvidia-smi`. GPU utilization is nowhere near 100%, and rarely goes above about 5%.

**If the current behavior is a bug, please provide the steps to reproduce.**

I am using a custom dataset, so I cannot provide a reproducible example. However, as noted above, I've confirmed that other deep models with O(millions) of parameters trains very fast on this same hardware and dataset using an identical pipeline.

**Expected behavior**

Training should take no more than ~1min per epoch, or GPU utilization should be very high.

**Screenshots**

**Other relevant information:**
python version: 3.6
Operating System: linux

**Additional context**
Other hyperparameters:

`'max_epochs': 80, 'patience': 10, 'batch_size': 128, 'virtual_batch_size': 16, optimizer_fn: adam, cat_emb_dim: 4, learning_rate: 0.001,  dropout_prob: 0.33`

All other hyperparameters are default values.

**Comment by Optimox** [comment]
Your batch size and virtual batch size are extremely small. So the GPU will only receive extremely small matrices. There is no way to get the most out of your GPU with such a small batch size.

The original paper says that you can train tabnet with a batch size of around 10% of your training data. I would recommend to try different batch sizes (BS) and virtual batch sizes (VBS) as follow:
- BS=1024, VBS=256
- BS=2048, VBS=256, 512
- BS=4096, VBS=256, 512
- BS=8192, VBS=256, 512
- BS=16384, VBS=256, 512, 1024

You should see a dramatic improvement in training speed. There might be a trade off between speed and performance however, that's why you might want to try different settings.

**Comment by jpgard** [comment]
Wow, you were right, thank you for the helpful reply!! I missed that important detail in the paper. The speedup in training is essentially linear in batch size, up to BS=16384 (I did not try higher, yet).
