### ISSUE TITLE
Adversarial attack on TabNet model

### ISSUE THREAD

**Issue by viketan** [dreamquark-ai/tabnet#393]
## Feature request

**What is the expected behavior?**
I want to perform the adversarial attack on TabNet. Also, As a defense mechanism to make the robust this kind of attack, going for Adversarial Training.

**What is the motivation or use case for adding/changing the behavior?**
I have found examples of adversarial attacks on images. Almost none for tabular data. This Adversarial Training requires a model of a neural network. Now, we have one. We can try this if possible.

**How should this be implemented in your opinion?**
For Adversarial attacks and Training, I was thinking of going by the tool known as Adversarial Robustness Toolbox(ART). We just have to make TabNet compatible with ART.

**Are you willing to work on this yourself?**
yes, I would love to make contribution on this.

**Comment by Optimox** [comment]
@viketan this is an interesting topic but it's very general and does not relate specifically with TabNet.

Batch augmentations are now available since https://github.com/dreamquark-ai/tabnet/commit/6d0485f58bd1028cffd195d9e27eb97915b9cb2c, this might be a way of making a model robust to "adversarial attacks" without adding anything to the repository.

Feel free to open a PR to discuss concretely on a piece of code.
