### ISSUE TITLE
BUG: Pretraining example does not work

### ISSUE THREAD

**Issue by canbooo** [dreamquark-ai/tabnet#425]
**Describe the bug**

[pretraining example](https://github.com/dreamquark-ai/tabnet/blob/develop/pretraining_example.ipynb) does not work due to possibly outdated keywords `n_shared_decoder` and `n_indep_decoder`

**What is the current behavior?**
The [notebook](https://github.com/dreamquark-ai/tabnet/blob/develop/pretraining_example.ipynb)  does not run

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run the [pretraining notebook](https://github.com/dreamquark-ai/tabnet/blob/develop/pretraining_example.ipynb) 
2. See the `TypeError: __init__() got an unexpected keyword argument 'n_shared_decoder' ` at cell 10.

**Expected behavior**

Example notebooks should run without error and should not require modification

**Other relevant information:**
poetry version:  1.1.13
python version:  3.9.10
Operating System:  Linux
Additional tools:

**Comment by Optimox** [comment]
The code works, that's why we have CI.

The problem is probably that you are running the develop branch notebook with the master branch code.

Either look at the master branch notebook or use the code from development branch.

By default the github page is in the develop branch, which can be quite confusing.

**Comment by canbooo** [comment]
You are right, my bad. In my defence, it **is** weird to have develop as the default branch.
