### ISSUE TITLE
Multi-class output in binary classification

### ISSUE THREAD

**Issue by meechos** [dreamquark-ai/tabnet#79]
The original tabnet classifier by google is hard-coded to pass predictions in a multi-class format, regardless of whether `num_classes` is 2.

Would you know if the above means
- there are two output neurons in the model
- performance is affected for binary classification problems? 

Is your implementation similar in this aspect?

**Comment by Optimox** [comment]
Hello @meechos,

I'm not sure to understand your question exactly.

The google implementation is indeed hard coded and you can't use their code for any dataset without changes.

Our implementation is scikit compatible which means that if you use `TabNetClassifier` you can do binary classification or multi class classification without having anything to do. Currently in tabnet, if you have a binary classification problem the model is going to early stop on AUC, otherwise early stopping is done on accuracy.

About number of neurons, in order to have consistent behavior between binary and multi class, the last layer outputs of softmax of size `num_classes` so for binary classification you do have two neurons at the end, one for probability of being 0 and the other one for probability of being 1.

I don't see any concerns about performances.

Does this answer your question?

**Comment by meechos** [comment]
Thank you @optimox, that makes sense.

I raised this as in previous experiments with google's codebase I was getting different performance if the labels were passed as `oneHot` and otherwise. But I agree that a two neuron output with a `softmax` should be the same as a single neuron output with a `sigmoid`.

> if you have a binary classification problem the model is going to early stop on AUC, otherwise early stopping is done on accuracy.

On this interesting note, would a fork make sense to switch that to `average_precision_score`? I am dealing with ultra imbalanced datasets `ratio<0.01`.

**Comment by Optimox** [comment]
I guess next step would be to add callbacks that allows you to early stop on any custom metric.
